### ISSUE TITLE
[Feat] 메세지 화면 구현

### ISSUE THREAD

**Issue by HAERYN** [TecheerBootios/RUAlone-iOS#8]
**어느 유저 스토리에 대한 작업(기능)인가요?**
사용자는 메세지를 주고 받고 모아볼 수 있습니다.

**작업(기능)에 대한 상세 내용을 정의해주세요**
사용자 메세지 목록 정리
메세지 화면 구현

**기타 내용**
![이미지 2022  12  19  오전 2 33](https://user-images.githubusercontent.com/81466548/208311354-c21a52d6-9701-4fc9-a673-7baf719b15b3.jpg)

**Comment by KKodiac** [comment]
채팅 **기능**을 위한 Sendbird SDK와 SwiftUI 연동은 #10 에서 맡아 진행하겠습니다!
